import argparse
# uni3d_config : Namespace(batch_size:32, beta1:0.9, beta2:0.999, 
#                          cache_dir:None, ckpt_path:'/root/autodl-tmp/ULIP_download/Uni3D/modelzoo/uni3d-g/scan/model.pt', 
#                          clip_model:'EVA02-E-14-plus', copy_codebase:False, ddp_static_graph:False, debug:False, 
#                          device:'cuda:0', disable_amp:False, dist_backend:'nccl', dist_url:'env://', 
#                          drop_path_rate:0.0, drop_rate:0.0, embed_dim:1024, enable_deepspeed:False, 
#                          epochs:32, eps:1e-08, eval_freq:1, evaluate_3d:True, force_patch_dropout:None, 
#                          gather_with_grad:False, grad_accumulation_steps:1, grad_checkpointing:False, 
#                          grad_clip_norm:None, group_size:64, image_mean:None, image_std:None, is_large:False, 
#                          ld:1.0, local_loss:False, lock_pointcloud:False, log_local:False, logs:'./logs/', 
#                          lr:0.0005, model:'create_uni3d', name:None, no_set_device_rank:False, 
#                          npoints:10000, num_group:512, openshape_setting:False, 
#                          optimizer:'adamw', output_dir:'./outputs', patch_dropout:0.0, pc_encoder_dim:512, pc_feat_dim:1408, 
#                          pc_model:'eva_giant_patch14_560', point_ld:None, point_lr:None, point_wd:None, precision:'amp', 
#                          pretrain_dataset_name:'shapenet', pretrain_dataset_prompt:'shapenet_64', 
#                          pretrained:'/path/to/clip_model/open_clip_pytorch_model.bin', pretrained_pc:'', 
#                          print_freq:10, resume:None, save_frequency:1, save_interval:100, save_most_recent:False, seed:0, 
#                          skip_scheduler:False, smoothing:0, start_epoch:0, text_ld:None, text_lr:None, text_wd:None, 
#                          update_freq:1, use_bn_sync:False, use_embed:False, use_height:False, use_lvis:False, 
#                          validate_dataset_name:'modelnet40_openshape', validate_dataset_name_lvis:'objaverse_lvis_openshape', 
#                          validate_dataset_name_scanobjnn:'scanobjnn_openshape', validate_dataset_prompt:'modelnet40_64', 
#                          visual_ld:None, visual_lr:None, visual_wd:None, wandb:False, wandb_notes:'', 
#                          wandb_project_name:'open-clip', wandb_runid:None, warmup:10000, wd:0.2, workers:4, zero_stage:1)

cfg_dict = {
    'batch_size':32, 'beta1':0.9, 'beta2':0.999, 
    'cache_dir':None, 'ckpt_path':'', 
    'clip_model':'EVA02-E-14-plus', 'copy_codebase':False, 'ddp_static_graph':False, 'debug':False, 
    'device':'cuda:0', 'disable_amp':False, 'dist_backend':'nccl', 'dist_url':'env://', 
    'drop_path_rate':0.0, 'drop_rate':0.0, 'embed_dim':1024, 'enable_deepspeed':False, 
    'epochs':32, 'eps':1e-08, 'eval_freq':1, 'evaluate_3d':True, 'force_patch_dropout':None, 
    'gather_with_grad':False, 'grad_accumulation_steps':1, 'grad_checkpointing':False, 
    'grad_clip_norm':None, 'group_size':64, 'image_mean':None, 'image_std':None, 'is_large':False, 
    'ld':1.0, 'local_loss':False, 'lock_pointcloud':False, 'log_local':False, 'logs':'./logs/', 
    'lr':0.0005, 'model':'create_uni3d', 'name':None, 'no_set_device_rank':False, 
    'npoints':10000, 'num_group':512, 'openshape_setting':False, 
    'optimizer':'adamw', 'output_dir':'./outputs', 'patch_dropout':0.0, 'pc_encoder_dim':512, 'pc_feat_dim':1408, 
    'pc_model':'eva_giant_patch14_560', 'point_ld':None, 'point_lr':None, 'point_wd':None, 'precision':'amp', 
    'pretrain_dataset_name':'shapenet', 'pretrain_dataset_prompt':'shapenet_64', 
    'pretrained':'/path/to/clip_model/open_clip_pytorch_model.bin', 'pretrained_pc':'', 
    'print_freq':10, 'resume':None, 'save_frequency':1, 'save_interval':100, 'save_most_recent':False, 'seed':0, 
    'skip_scheduler':False, 'smoothing':0, 'start_epoch':0, 'text_ld':None, 'text_lr':None, 'text_wd':None, 
    'update_freq':1, 'use_bn_sync':False, 'use_embed':False, 'use_height':False, 'use_lvis':False, 
    'validate_dataset_name':'modelnet40_openshape', 'validate_dataset_name_lvis':'objaverse_lvis_openshape', 
    'validate_dataset_name_scanobjnn':'scanobjnn_openshape', 'validate_dataset_prompt':'modelnet40_64', 
    'visual_ld':None, 'visual_lr':None, 'visual_wd':None, 'wandb':False, 'wandb_notes':'', 
    'wandb_project_name':'open-clip', 'wandb_runid':None, 'warmup':10000, 'wd':0.2, 'workers':4, 'zero_stage':1
}

uni3d_config = argparse.Namespace(**cfg_dict)